name: Syslog Logger
version: 1.0.9
slug: udp_logger
description: Listens for UDP (syslog) log messages on port udp/514 and writes them to a file.
startup: application
boot: auto
homeassistant: 2021.12.0
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
options: {}
schema: {}
map:
  - share:rw

