name: Syslog Logger
version: 1.1.5
slug: udp_logger
description: Listens for UDP and TCP (syslog) log messages on port udp/514 (by default and can be changed to another port) and writes them to a file
startup: application. The port is always the same for udp and tcp (so if you change one, the other one will change as well)
boot: auto
homeassistant: 2021.12.0
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
options:
  trigger_patterns:
    - "ALERT"
    - "ERROR"
  ha_token: ""
  max_days: 7
  port: 514
schema:
  trigger_patterns:
    - str
  ha_token: password
  max_days: int(1,30)
  port: int(10,65535)
map:
  - share:rw