name: Syslog Logger
version: 1.1.4
slug: udp_logger
description: Listens for UDP (syslog) log messages on port udp/514 and writes them to a file
startup: application
boot: auto
homeassistant: 2021.12.0
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
options:
  trigger_patterns:
    - "ALERT"
    - "ERROR"
  ha_token: ""
  max_days: 7
  port: 514
schema:
  trigger_patterns:
    - str
  ha_token: password
  max_days: int(1,30)
  port: int (10,65535)
map:
  - share:rw