name: Syslog Logger
version: 1.1.0
slug: udp_logger
description: Listens for UDP (syslog) log messages on port udp/514 and writes them to a file.
startup: application
boot: auto
homeassistant: 2021.12.0
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
options:
  trigger_patterns:
    - ALERT
    - ERROR
  ha_url: "http://homeassistant.local:8123"
  ha_token: ""
  max_days: 7

schema:
  trigger_patterns:
    - str
  ha_url: str
  ha_token: password
  max_days: int
map:
  - share:rw

